theme = "solarized-dark"
icons = "awesome"
#[theme]
#file = "/home/z0/.config/i3/solarized-dark.toml"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "net"
device = "enp1s0"
ssid = false
ip = false
speed_up = true
speed_down = true
bitrate = false

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m} {5m} {15m}"

#[[block]]
#block = "battery"
#format = "{percentage}%"

#[[block]]
#block = "sound"
#driver = "pulseaudio"
#step_width = 10

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
